<?
if(!defined('B_PROLOG_INCLUDED') || B_PROLOG_INCLUDED !== true) die();

$arServices = array(
	'thematics' => array(
		'NAME' => GetMessage('SERVICE_PREPARE_DATA'),
		'MODULE_ID' => 'fileman',
		'STAGES' => array(
			'check.php',
			'download.php',
			'clear.php',
			'unzip.php',
		),
	),
	'main' => array(
		'NAME' => GetMessage('SERVICE_MAIN_SETTINGS'),
		'STAGES' => array(
			'public.php',
			'template.php',
			'theme.php',
			'menu.php',
			'settings.php',
		),
	),
	'iblock' => Array(
		'NAME' => GetMessage('SERVICE_IBLOCK_DEMO_DATA'),
		"STAGES" => Array(
			"types.php",
			"hl_contact.php",
			"hl_contact_content.php",
			"hl_services.php",
			"hl_services_content.php",
			"complects.php",
			"front_tizers.php",
			"regions.php",
			"megamenu.php",
			"mainblocks.php",
			"banner_types.php",
			"gallery.php",
			"docs.php",
			"sku.php",
			"bottom_icons.php",
			"advtbig.php",
			"banners.php",
			"nadzor.php",
			"vacancy.php",
			"faq.php",
			"brands.php",
			"licenses.php",
			"history.php",
			"contact.php",
			"adv_content.php",
			"company.php",
			"banners_fon.php",
			"reviews.php",
			"price.php",
			"partners.php",
			"articles.php",
			"news.php",
			"sales.php",
			"staff.php",
			"services.php",
			"catalog_part1.php",
			"catalog_part2.php",
			"catalog_info.php",
			"news_personal.php",
			"landing.php",
			"marketings.php",
			"banners_with_text.php",
			"forms.php",
			"links.php",
		),
	),
	'form' => array(
		'NAME' => GetMessage('SERVICE_FORM_DEMO_DATA'),
		'STAGES' => array(
			'toorder.php',
			'director.php',
			'order_product.php',
			'order_services.php',
			'resume.php',
			'question.php',
			'callback.php',
			'feedback.php',
			'quick_buy.php',
			'online.php',
			'online_short.php',
			//'errors_updates.php',
		)
	),
	// 'search' => array(
	// 	'NAME' => GetMessage('SERVICE_SEARCH'),
	// 	'STAGES' => array(
	// 		'search.php',
	// 	),
	// ),
);?>